### ISSUE TITLE
spam entries in upcoming workshops listing

### ISSUE THREAD

**Issue by Trott** [nodeschool/organizers#172]
The March 30 2015 nodeJSguru event appears to be spam that has nothing to do with NodeSchool. It's a commercial Node training course offered for $301

The April 10 2015 HashTag and April 3 2015 Medellin events link to sites with no NodeSchool (or even JavaScript) content. I'd argue that if the link doesn't take the user somewhere that tells them about the NodeSchool event, it should be removed.

**Comment by blakmatrix** [comment]
Do you have the links to those?

-- 
Farrin A. Reid
http://www.linkedin.com/in/farrinreid

**Comment by Trott** [comment]
The links are currently on the front page of nodeschool.io under Upcoming Workshops.

nodeJSguru: http://nodejsguru.com/course
HashTag: http://www.hashtagofficial.in/
Medellin: http://nodeschool.strikingly.com/

**Comment by jasonrhodes** [comment]
@Trott good catch. I've moved those events to another tab of the Google sheet so they come off of the events page, but if for some reason they need to be re-instated with edited links (say they were hacked or something), they can be easily put back.

**Comment by blakmatrix** [comment]
@jasonrhodes Ummm, looking at the site I see those three events and nothing else.
![image of hacked events](http://i.imgur.com/NTCPvZy.png)

**Comment by blakmatrix** [comment]
Fixed by someone!

**Comment by jasonrhodes** [comment]
Ha yeah it wasn't fixed, it was alternating between the real sheet and the spam sheet which is why I thought it worked and you saw it broken. I moved them out of that Google sheet altogether and _now_ it's fixed. Thanks. :)
